### PR TITLE
refactor: put python code in module

### PR DESCRIPTION
**Pull request by marvinmarnold**
I made these changes while trying to get things running and understand what is going on. @ayyubibrahimi can you confirm which methods to invoke in order to produce the results? What units are the results in?

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
I used the method `neighbors`. As currently written, it outputs the distances for a camera and the closest call for service. The scipy library is required to run `neighbors`.

The method is calculating the euclidean distance between the given points. Reading up more now on what unit the KDTree method in the spicy library returns when it calculates the nearest neighbor.

**Comment by ayyubibrahimi** [comment]
Just pushed a new script, `distances.py`, that contains a method to calculate the nearest neighbor in yards.  Do the results line up with what you expected?

**Comment by ayyubibrahimi** [comment]
@marvinmarnold Added to your refactoring work. Any thoughts/next steps for these or related data?

**Comment by marvinmarnold** [comment]
I'll take a look at this next week. Thanks for the nudge.

**Pull request closed without merging**
